<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getMeteringSettings</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4gCgpJRGF0YUN1cnNvciBjdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3Io
KTsgClN0cmluZyBkZWZhdWx0TmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiZGVm
YXVsdE5hbWUiKTsKCi8vIHByb2Nlc3MKClN0cmluZyBtZXRlcmluZ0ZpbGUgPSBTeXN0ZW0uZ2V0
UHJvcGVydHkoIndhdHQuc2VydmljZS5hbGVydHMubWV0ZXJpbmcuZmlsZSIpOwpTdHJpbmcgZW50
aXR5ID0gU3lzdGVtLmdldFByb3BlcnR5KCJ3YXR0LnNlcnZpY2UuYWxlcnRzLm1ldGVyaW5nLmVu
dGl0eSIpOwpTdHJpbmcgcHJvZHVjdCA9IFN5c3RlbS5nZXRQcm9wZXJ0eSgid2F0dC5zZXJ2aWNl
LmFsZXJ0cy5tZXRlcmluZy5wcm9kdWN0Iik7ClN0cmluZyBydW50aW1lSWQgPSBTeXN0ZW0uZ2V0
UHJvcGVydHkoIndhdHQuc2VydmljZS5hbGVydHMubWV0ZXJpbmcucnVudGltZUlkIik7CgovLyBw
aXBlbGluZSBvdXQKCmlmIChwcm9kdWN0ICE9IG51bGwpCglJRGF0YVV0aWwucHV0KGN1cnNvciwg
InByb2R1Y3QiLCBwcm9kdWN0KTsKZWxzZQoJSURhdGFVdGlsLnB1dChjdXJzb3IsICJwcm9kdWN0
IiwgIlBJRSIpOwoKaWYgKGVudGl0eSAhPSBudWxsKQoJSURhdGFVdGlsLnB1dChjdXJzb3IsICJl
bnRpdHkiLCBlbnRpdHkpOwplbHNlCglJRGF0YVV0aWwucHV0KGN1cnNvciwgImVudGl0eSIsICJu
b3Qgc2V0IC0gcGxlYXNlIHByb3ZpZGUgZXh0ZW5kZWQgc2V0dGluZyB3YXR0LnNlcnZpY2UuYWxl
cnRzLm1ldGVyaW5nLmVudGl0eSIpOwoKaWYgKHJ1bnRpbWVJZCAhPSBudWxsKQoJSURhdGFVdGls
LnB1dChjdXJzb3IsICJydW50aW1lSWQiLCBydW50aW1lSWQpOwplbHNlCglJRGF0YVV0aWwucHV0
KGN1cnNvciwgInJ1bnRpbWVJZCIsICJub3Qgc2V0IC0gcGxlYXNlIHByb3ZpZGUgZXh0ZW5kZWQg
c2V0dGluZyB3YXR0LnNlcnZpY2UuYWxlcnRzLm1ldGVyaW5nLnJ1bnRpbWVJZCIpOwppZiAobWV0
ZXJpbmdGaWxlICE9IG51bGwpCglJRGF0YVV0aWwucHV0KGN1cnNvciwgIm1ldGVyaW5nRmlsZSIs
IG1ldGVyaW5nRmlsZSk7CmVsc2UKCUlEYXRhVXRpbC5wdXQoY3Vyc29yLCAibWV0ZXJpbmdGaWxl
IiwgZGVmYXVsdE5hbWUpOwoKY3Vyc29yLmRlc3Ryb3koKTsKCQ==</value>
</Values>
