<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getServiceAnalytics</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4gCgpJRGF0YUN1cnNvciBjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0
cmluZyBzZXJ2aWNlID0gSURhdGFVdGlsLmdldFN0cmluZyhjLCAic2VydmljZSIpOwpTdHJpbmcg
c291cmNlID0gSURhdGFVdGlsLmdldFN0cmluZyhjLCAic291cmNlIik7CgovLyBwcm9jZXNzCgps
b25nIHlzY2FsZSA9IDIwMDsgCgpTb3VyY2Ugc3JjID0gc291cmNlICE9IG51bGwgPyBTb3VyY2Uu
dmFsdWVPZihzb3VyY2UpIDogbnVsbDsKCmlmIChzZXJ2aWNlICE9IG51bGwpIHsKCUlEYXRhVXRp
bC5wdXQoYywgInJlc3VsdHMiLCBBbGxDb21wdXRlcnMuaW5zdGFuY2Uuc2VydmljZVN0YXRpc3Rp
Y3NGb3Ioc2VydmljZSwgc3JjLCB5c2NhbGUpKTsKfSBlbHNlIHsKCUlEYXRhVXRpbC5wdXQoYywg
InJlc3VsdHMiLCBBbGxDb21wdXRlcnMuaW5zdGFuY2Uuc2VydmljZXNGb3Ioc3JjKSk7Cn0KCi8v
IHBpcGVsaW5lIG91dAoJCQpjLmRlc3Ryb3koKTsKCQ==</value>
</Values>
