<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">average</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3Ry
aW5nIHNvdXJjZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoYywgInNvdXJjZSIpOwpTdHJpbmcgdW9t
ID0gSURhdGFVdGlsLmdldFN0cmluZyhjLCAidW9tIik7Ck9iamVjdFtdIHJ1bGVzID0gKE9iamVj
dFtdKSBJRGF0YVV0aWwuZ2V0KGMsICJydWxlcyIpOwoKLy8gY3JlYXRlIG5ldyBBdmVyYWdlIHJ1
bGUgamF2YSBPYmplY3QgdG8gdXNlIHdpdGggYSBjb21wdXRlcgoKQXZlcmFnZSBhdiA9IG5ldyBB
dmVyYWdlKFNvdXJjZS52YWx1ZU9mKHNvdXJjZSkpOwoKaWYgKHJ1bGVzICE9IG51bGwpIHsKCWZv
ciAoT2JqZWN0IHJ1bGUgOiBydWxlcykgewoJCWF2LmFkZFJ1bGUoKFJ1bGU8RG91YmxlPikgcnVs
ZSk7Cgl9Cn0KCi8vIHBpcGVsaW5lIG91CgpJRGF0YVV0aWwucHV0KGMsICJjb21wdXRlQXZlcmFn
ZSIsIGF2KTsKYy5kZXN0cm95KCk7Cgk=</value>
</Values>
