<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">recordAuditEndEvent</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3RyaW5n
IGlkID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNvciwgIlRJRCIpOwpTdHJpbmcg
c2VydmljZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJzb3IsICJzZXJ2aWNlIik7
Ci8vU3RyaW5nIHRpbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29yLCAidGlt
ZSIpOwpTdHJpbmcgcmVzdWx0ID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNvciwg
InJlc3VsdCIpOwoKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoKbG9uZyB0aW1lID0gcmVzdWx0
ID09ICJFbmRlZCIgPyBuZXcgRGF0ZSgpLmdldFRpbWUoKSA6IC0xOwoKU3lzdGVtLm91dC5wcmlu
dGxuKCI8PDw8PDw8PDw8PDw8PDw8PDw8PCByZWNvcmRpbmcgZW5kIGV2ZW50ICdkdXJhdGlvbicg
Zm9yICIgKyBzZXJ2aWNlKTsKCmFwcGx5Q29tcHV0ZXJzKCJBdWRpdCBFdmVudCIsIGlkLCBzZXJ2
aWNlLCAiZHVyYXRpb24iLCB0aW1lKTsKClN5c3RlbS5vdXQucHJpbnRsbigiPDw8PDw8PDw8PDw8
PDw8PDw8PDwgcmVjb3JkaW5nIGVuZCBldmVudCAnY291bnQnIGZvciAiICsgc2VydmljZSk7Cgph
cHBseUNvbXB1dGVycygiQXVkaXQgRXZlbnQiLCBudWxsLCBzZXJ2aWNlLCB0aW1lID4gMCA/ICJj
b3VudCIgOiAiZmFpbGVkIiwgMSk7Cgk=</value>
</Values>
