<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">channels</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFbXSBjaGFubmVscyA9IG51bGw7Cgp0cnkgewoJCglJRGF0YSByZXN1bHRzID0gU2Vydmlj
ZS5kb0ludm9rZSgicHViLmFsZXJ0IiwgImNoYW5uZWxzIiwgSURhdGFGYWN0b3J5LmNyZWF0ZSgp
KTsKCUlEYXRhQ3Vyc29yIHJjID0gcmVzdWx0cy5nZXRDdXJzb3IoKTsKCWNoYW5uZWxzID0gSURh
dGFVdGlsLmdldElEYXRhQXJyYXkocmMsICJjaGFubmVscyIpOwoJcmMuZGVzdHJveSgpOwoJCn0g
Y2F0Y2goRXhjZXB0aW9uIGUpIHsKCS8vIGRvIG5vdyd0Cn0KCklEYXRhQ3Vyc29yIGMgPSBwaXBl
bGluZS5nZXRDdXJzb3IoKTsKCmlmIChjaGFubmVscyAhPSBudWxsKSB7CgkKCUlEYXRhVXRpbC5w
dXQoYywgImNoYW5uZWxzIiwgY2hhbm5lbHMpOwoJSURhdGFVdGlsLnB1dChjLCAiaXNBdmFpbGFi
bGUiLCB0cnVlKTsKfSBlbHNlIHsKCUlEYXRhVXRpbC5wdXQoYywgImlzQXZhaWxhYmxlIiwgZmFs
c2UpOwp9CgpjLmRlc3Ryb3koKTs=</value>
</Values>
