<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">_removeFromList</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KSURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJp
bmcgaW5kZXggPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGMsICJpbmRleCIpOwpJRGF0YVtdIGluTGlz
dCA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KGMsICJpbkxpc3QiKTsKCi8vIHByb2Nlc3MKCmlu
dCBpID0gLTE7CklEYXRhW10gb3V0TGlzdCA9IGluTGlzdDsKCnRyeSB7IGkgPSBJbnRlZ2VyLnBh
cnNlSW50KGluZGV4KSAtIDE7IH0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7fQoKaWYgKGluTGlzdCAh
PSBudWxsICYmIGkgPj0wICYmIGkgPCBpbkxpc3QubGVuZ3RoKSB7CgkKCWlmIChpbkxpc3QubGVu
Z3RoID09IDEpIHsKCQlvdXRMaXN0ID0gbmV3IElEYXRhWzBdOwoJfSBlbHNlIHsKCQlvdXRMaXN0
ID0gbmV3IElEYXRhW2luTGlzdC5sZW5ndGgtMV07CgkJaW50IHogPSAwOwoJCWZvciAoaW50IHEg
PSAwOyBxIDwgaW5MaXN0Lmxlbmd0aDsgcSsrKSB7CgkJCQoJCQlpZiAocSAhPSBpKSB7CgkJCQlv
dXRMaXN0W3orK10gPSBpbkxpc3RbcV07CgkJCX0KCQl9Cgl9Cn0KCi8vIHBpcGVsaW5lIG91dAoK
SURhdGFVdGlsLnB1dChjLCAib3V0TGlzdCIsIG91dExpc3QpOwpjLmRlc3Ryb3koKTs=</value>
</Values>
