<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">_removeFromList</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3Ry
aW5nIGluZGV4ID0gSURhdGFVdGlsLmdldFN0cmluZyhjLCAiaW5kZXgiKTsKSURhdGFbXSBpbkxp
c3QgPSBJRGF0YVV0aWwuZ2V0SURhdGFBcnJheShjLCAiaW5MaXN0Iik7CgovLyBwcm9jZXNzaW5n
CgppbnQgaSA9IC0xOwpJRGF0YVtdIG91dExpc3QgPSBpbkxpc3Q7Cgp0cnkgeyBpID0gSW50ZWdl
ci5wYXJzZUludChpbmRleCkgLSAxOyB9IGNhdGNoIChFeGNlcHRpb24gZSkge30KCmlmIChpbkxp
c3QgIT0gbnVsbCAmJiBpID49MCAmJiBpIDwgaW5MaXN0Lmxlbmd0aCkgewoJCglpZiAoaW5MaXN0
Lmxlbmd0aCA9PSAxKSB7CgkJb3V0TGlzdCA9IG5ldyBJRGF0YVswXTsKCX0gZWxzZSB7CgkJb3V0
TGlzdCA9IG5ldyBJRGF0YVtpbkxpc3QubGVuZ3RoLTFdOwoJCWludCB6ID0gMDsKCQlmb3IgKGlu
dCBxID0gMDsgcSA8IGluTGlzdC5sZW5ndGg7IHErKykgewoJCQkKCQkJaWYgKHEgIT0gaSkgewoJ
CQkJb3V0TGlzdFt6KytdID0gaW5MaXN0W3FdOwoJCQl9CgkJfQoJfQp9CgovLyBwaXBlbGluZSBv
dXQKCklEYXRhVXRpbC5wdXQoYywgIm91dExpc3QiLCBvdXRMaXN0KTsKYy5kZXN0cm95KCk7</value>
</Values>
