<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">_removeFromList</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3Ry
aW5nIGluZGV4ID0gSURhdGFVdGlsLmdldFN0cmluZyhjLCAiaW5kZXgiKTsKSURhdGFbXSBpbkxp
c3QgPSBJRGF0YVV0aWwuZ2V0SURhdGFBcnJheShjLCAiaW5MaXN0Iik7CgovLyBwcm9jZXNzaW5n
CgppbnQgaSA9IC0xOwpJRGF0YVtdIG91dExpc3QgPSBpbkxpc3Q7Cgp0cnkgeyBpID0gSW50ZWdl
ci5wYXJzZUludChpbmRleCkgLSAxOyB9IGNhdGNoIChFeGNlcHRpb24gZSkge30KCmlmIChpbkxp
c3QgIT0gbnVsbCAmJiBpID49MCAmJiBpIDwgaW5MaXN0Lmxlbmd0aCkgewoKaWYgKGluTGlzdC5s
ZW5ndGggPT0gMSkgewpvdXRMaXN0ID0gbmV3IElEYXRhWzBdOwp9IGVsc2UgewpvdXRMaXN0ID0g
bmV3IElEYXRhW2luTGlzdC5sZW5ndGgtMV07CmludCB6ID0gMDsKZm9yIChpbnQgcSA9IDA7IHEg
PCBpbkxpc3QubGVuZ3RoOyBxKyspIHsKCmlmIChxICE9IGkpIHsKCW91dExpc3RbeisrXSA9IGlu
TGlzdFtxXTsKfQp9Cn0KfQoKLy8gcGlwZWxpbmUgb3V0CgpJRGF0YVV0aWwucHV0KGMsICJvdXRM
aXN0Iiwgb3V0TGlzdCk7CmMuZGVzdHJveSgpOw==</value>
</Values>
