<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">unregisterComputers</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3Ry
aW5nIGV2ZW50VHlwZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoYywgIkV2ZW50VHlwZSIpOwpJRGF0
YSBzdWJzY3JpYmVycyA9IElEYXRhVXRpbC5nZXRJRGF0YShjLCAiU3Vic2NyaWJlcnMiKTsKYy5k
ZXN0cm95KCk7CgovLyBwcm9jZXNzCgpjID0gc3Vic2NyaWJlcnMuZ2V0Q3Vyc29yKCk7CmMuZmly
c3QoKTsKZG8gewoJU3RyaW5nIGlkID0gYy5nZXRLZXkoKTsKCUlEYXRhIHN1YnNjcmliZXIgPSAo
SURhdGEpIGMuZ2V0VmFsdWUoKTsKCQkJCQoJaWYgKHN1YnNjcmliZXIgIT0gbnVsbCkgewoJCgkJ
U3lzdGVtLm91dC5wcmludGxuKCJ1bnJlZ2lzdGVyaW5nIGxpc3RlbmVyIGZvciAiICsgaWQgKyAi
IGFuZCAiICsgZXZlbnRUeXBlKTsKCgkJSURhdGFDdXJzb3Igc2MgPSBzdWJzY3JpYmVyLmdldEN1
cnNvcigpOwoJCVN0cmluZyBmaWx0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHNjLCAiRmlsdGVy
Iik7CgkJU3RyaW5nIHNlcnZpY2UgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHNjLCAiU2VydmljZSIp
OwoKCQlzYy5kZXN0cm95KCk7CgkJCgkJaWYgKHNlcnZpY2UuZXF1YWxzKCJ3eC5zZXJ2aWNlLmFs
ZXJ0cy5ldmVudHM6bWFuYWdlQXVkaXRFdmVudHMiKSB8fCBzZXJ2aWNlLmVxdWFscygid3guc2Vy
dmljZS5hbGVydHMuZXZlbnRzOm1hbmFnZUV4Y2VwdGlvbkV2ZW50cyIpKQoJCQlkZWxldGVTdWJz
Y3JpYmVyKGV2ZW50VHlwZSwgaWQpOwoJfQp9IHdoaWxlIChjLm5leHQoKSk7Cgk=</value>
</Values>
