<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">unregisterComputers</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3Ry
aW5nIGV2ZW50VHlwZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoYywgIkV2ZW50VHlwZSIpOwpJRGF0
YSBzdWJzY3JpYmVycyA9IElEYXRhVXRpbC5nZXRJRGF0YShjLCAiU3Vic2NyaWJlcnMiKTsKYy5k
ZXN0cm95KCk7CgovLyBwcm9jZXNzCgpjID0gc3Vic2NyaWJlcnMuZ2V0Q3Vyc29yKCk7CmMuZmly
c3QoKTsKZG8gewoJU3RyaW5nIGlkID0gYy5nZXRLZXkoKTsKCUlEYXRhIHN1YnNjcmliZXIgPSAo
SURhdGEpIGMuZ2V0VmFsdWUoKTsKCQkJCQoJaWYgKHN1YnNjcmliZXIgIT0gbnVsbCkgewoJCgkJ
U3lzdGVtLm91dC5wcmludGxuKCJ1bnJlZ2lzdGVyaW5nIGxpc3RlbmVyIGZvciAiICsgaWQgKyAi
IGFuZCAiICsgZXZlbnRUeXBlKTsKCgkJSURhdGFDdXJzb3Igc2MgPSBzdWJzY3JpYmVyLmdldEN1
cnNvcigpOwoJCVN0cmluZyBmaWx0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHNjLCAiRmlsdGVy
Iik7CgkJc2MuZGVzdHJveSgpOwoJCQoJCVN0cmluZyBmbHQgPSBldmVudFR5cGUgKyBmaWx0ZXI7
CgkJCgkJaWYgKGZpbHRlci5lbmRzV2l0aCgiLioiKSkgewoJCQlmbHQgPSBldmVudFR5cGUgKyBm
aWx0ZXIuc3Vic3RyaW5nKDAsIGZpbHRlci5sZW5ndGgoKS0yKTsKCQl9IGVsc2UgaWYgKGZpbHRl
ci5lbmRzV2l0aCgiKiIpKSB7CgkJCWZsdCA9IGV2ZW50VHlwZSArIGZpbHRlci5zdWJzdHJpbmco
MCwgZmlsdGVyLmxlbmd0aCgpLTEpOwoJCX0KCQkKCQlTeXN0ZW0ub3V0LnByaW50bG4oImZpbHRl
ciBpcyAiICsgZmx0ICsgIiAvICIgKyBpZCk7CgkJCgkJaWYgKGZsdCAhPSBudWxsICYmIF9kZWZh
dWx0LmdldChmbHQpICE9IG51bGwpIHsKCQkJCgkJCVN5c3RlbS5vdXQucHJpbnRsbigicmVtb3Zp
bmcgY29tcHV0ZXIiKTsKCQkJCgkJCXJlbW92ZVN1YnNjcmliZXIoaWQsIGZsdCk7CgkJfQoJfQp9
IHdoaWxlIChjLm5leHQoKSk7Cgk=</value>
</Values>
